events {
  worker_connections 1024;
}

http {
  upstream kv_cluster {
    server node-1:8080;
    server node-2:8080;
    server node-3:8080;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://kv_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}